### ISSUE TITLE
Wrong PUBLIC_FILES_PATH path in docs/gcp_filestore_migration.md

### ISSUE THREAD

**Issue by tormi** [wunderio/silta#101]
Currently `PUBLIC_FILES_PATH` value is defined as full path in [docs/gcp_filestore_migration.md](https://github.com/wunderio/silta/blob/master/docs/gcp_filestore_migration.md?plain=1#L81):

7. Add the original Drupal file paths as environment variables (ignore the private files path if the project doesn't have private file system enabled)
    ```yaml
    php:
      env:
        ...
        PUBLIC_FILES_PATH: /app/web/sites/default/files
    ```

Hovewer, the correct value for `$settings['file_public_path'] =` is `sites/default/files` as described in https://www.drupal.org/node/15368. Therefore it's not possible to use Silta default `PUBLIC_FILES_PATH` for public file system setup.
